# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# This Source Code Form is "Incompatible With Secondary Licenses", as
# defined by the Mozilla Public License, v. 2.0.

version: '2'
services:
  bugzilla:
    container_name: bugzilla-dev-dkl
    image: bugzilla/bugzilla-dev:dkl
    ports:
      - "80:80"
      - "5900:5900"
      - "8000:8000"
    volumes:
      - "/home/dkl/devel:/home/bugzilla/devel"
      - "/home/dkl/data/mysql:/var/lib/mysql"
      - "/home/dkl/data/tmp:/tmp"
    links:
      - elastic
  elastic:
    container_name: elastic
    image: elasticsearch:1
    volumes:
      - "/home/dkl/data/elastic:/usr/share/elasticsearch/data"
